_imagine:
    resource: .
    type:     imagine

notice_show:
    pattern:  /notice/show.json
    defaults: { _controller: AnimeDbAppBundle:Notice:show, _format: json }

notice_close:
    pattern:  /notice/{id}/close.json
    defaults: { _controller: AnimeDbAppBundle:Notice:close, _format: json }
    requirements:
        _method:  POST
        id:  \d+

notice_see_later:
    pattern:  /notice/see_later.json
    defaults: { _controller: AnimeDbAppBundle:Notice:seeLater, _format: json }
    requirements:
        _method:  POST


form_local_path:
    pattern:  /form/local_path.html
    defaults: { _controller: AnimeDbAppBundle:Form:localPath }

form_local_path_folders:
    pattern:  /form/local_path/folders.json
    defaults: { _controller: AnimeDbAppBundle:Form:localPathFolders, _format: json }

form_image:
    pattern:  /form/image.html
    defaults: { _controller: AnimeDbAppBundle:Form:image }

form_image_upload:
    pattern:  /form/imageUpload.json
    defaults: { _controller: AnimeDbAppBundle:Form:imageUpload, _format: json }
    requirements:
        _method:  POST


media_favicon:
    pattern:  /media/favicon/{host}.ico
    requirements:
        host: .+
    defaults: { _controller: AnimeDbAppBundle:Media:favicon }


command_exec:
    pattern:  /command/exec.html
    defaults: { _controller: AnimeDbAppBundle:Command:exec }
    methods:  [POST]
