doctrine:
    orm:
        dql:
            datetime_functions:
                datetime: AnimeDb\Bundle\AppBundle\DQL\Datetime

twig:
    form:
        resources: ['AnimeDbAppBundle:Form:fields.html.twig']

framework:
    templating:
        hinclude_default_template: 'AnimeDbAppBundle::hinclude.html.twig'

assetic:
    bundles: [ AnimeDbAppBundle ]
